### ISSUE TITLE
cloudera is not an easy application

### ISSUE THREAD

**Issue by 121onto** [j-delaney/easy-application#118]
Cloudera should be removed from this repository because their application form is long and because the tos are unfriendly to job seekers.

Cloudera's application is long.  It is  a multi-step form that requires the applicant to manually fill in data about previous employers and school background.  

Cloudera's tos are unfriendly to job seekers.  Cloudera's tos include an NDA, which job seekers must agree to before submitting their application.  The application obfuscates the fact that applicants are submitting to an NDA in two ways.  First, the next button scrolls down automatically so the applicant does not see NDA in the title "Cloudera Employment Application and NDA".  Second, the application combines this NDA as part of another form possibly making it unclear to applicants that they are submitting to an NDA.

**Comment by j-delaney** [comment]
@121onto Thanks for opening up this issue! I definitely want to make sure every company on this list is easy to apply to and provides a great experience for job-seekers and I really appreciate that you're helping with that!

Could you please attach some screenshots of the page(s) where you have to manually fill in information? I want to make sure I always have good documentation as to why a company is being removed to keep things fair.

**Comment by j-delaney** [comment]
Ping @121onto

**Comment by DannyMcwaves** [comment]
@121onto @j-delaney 
following @121onto  issue I tried to apply to cloudera and it was really simple.
More simpler than others I have seen. You just have to read the NDA, accept and 
then you go to a form where you fill in your name, place, email. 
The resume and the cover letter also comes in different formats. 
You can copy and paste, select from a cloud or upload from you computer.

Even though I have not gotten any response as to the status of my application, I
think it is very easy to apply to Cloudera.

Hope this helps

**Comment by 121onto** [comment]
I was unable to replicate my initial experience.  The application looks different from what I remember.  Hard to say what happened there.  Closing the issue for now.
