### ISSUE TITLE
New link for Cloudera in SF, CA

### ISSUE THREAD

**Issue by tommygebru** [j-delaney/easy-application#137]
http://jobs.jobvite.com/cloudera/jobs

**Comment by audip** [comment]
@j-delaney The old link points correctly to the careers page and so this issue can be closed.
The new link points to an exact page for JobsVite but that may change over time, sticking to the old link of Jobs page is better.

**Comment by j-delaney** [comment]
@audip Thanks for looking into that. Closing out.
