### ISSUE TITLE
New link for Clustrix in SF, CA

### ISSUE THREAD

**Issue by tommygebru** [j-delaney/easy-application#138]
http://www.clustrix.com/company/careers/openings/

**Comment by audip** [comment]
@j-delaney The old link points correctly to the careers page and so this issue can be closed.
The new link points to an exact page for Recruiter Box but that may change over time, sticking to the old link of Jobs page is better.

**Comment by j-delaney** [comment]
@audip Thanks for looking into that. Closing out.
