### ISSUE TITLE
New link for Couchsurfing in SF, CA

### ISSUE THREAD

**Issue by tommygebru** [j-delaney/easy-application#139]
https://couchsurfing.recruiterbox.com/

**Comment by vipuldcoder** [comment]
This is also not responsive website Can I fix it?

**Comment by cyclopes123** [comment]
Well I can access the website. It might be a network problem. I'm in South korea..

**Comment by audip** [comment]
The old link is to the careers page and so this issue can be closed.
The new link points to an exact page for Recruiter Box but that may change over time, sticking to the old link of Jobs page is better.

**Comment by j-delaney** [comment]
@audip Thanks for looking into that. Closing out.
