### ISSUE TITLE
New link for Counsyl in SF, CA

### ISSUE THREAD

**Issue by tommygebru** [j-delaney/easy-application#140]
https://www.counsyl.com/careers/

**Comment by j-delaney** [comment]
Thanks for noticing that! Would you like to open a Pull Request to fix it or would you prefer me to fix it and credit you in the commit description?

**Comment by vipuldcoder** [comment]
The website is totally Non responsive I would like file link so that i can fix it and make it screen responsive

**Comment by cyclopes123** [comment]
Like issue#139, I can access this website too..

**Comment by vipuldcoder** [comment]
I see the same issue again.

**Comment by j-delaney** [comment]
@vipuldcoder Could you explain what you mean by "non responsive"?

**Comment by jaycegregg0** [comment]
@vipuldcoder My guess is that it's due to connectivity problems between India and their servers as it appears to be working fine via US-based networks.

**Comment by audip** [comment]
This issue can be closed as the new link works correctly.

**Comment by j-delaney** [comment]
@audip Thanks for looking into that. Closing out.
