### ISSUE TITLE
Open links in new tab

### ISSUE THREAD

**Issue by kshiprakode** [j-delaney/easy-application#148]
Clicking on any of the links, opens them in the same browser tab.
Opening links in a new browser tab would be more efficient as it would reduce the number of back and forths in case a person is doing multiple applications.

I could open a Pull Request to fix this.

**Comment by j-delaney** [comment]
Great idea! If you opened a PR to fix this I would happily merge it in :)

**Comment by j-delaney** [comment]
Ping @kshiprakode . Still planning on opening a PR for this?
