### ISSUE TITLE
Multiple locations?

### ISSUE THREAD

**Issue by carsnwd** [j-delaney/easy-application#17]
Was trying to help out with the location branch, but some companies have multiple locations like Bitly for example is in Denver, San Francisco, and New York. Put them all down or?

**Comment by j-delaney** [comment]
Yeah, put them all down separated by a semicolon and in alphabetical order please. If the company supports remote we can treat that as a location too. Thanks for your help with adding locations!

**Comment by j-delaney** [comment]
I updated CONTRIBUTING.md to include this info
