### ISSUE TITLE
Gilt application not easy

### ISSUE THREAD

**Issue by rjayasin** [j-delaney/easy-application#171]
Applying requires creating an account, e.g. click apply now: https://www.gilt.com/careers/job/170003nb-2/

**Comment by j-delaney** [comment]
@rjayasin Could you please include some screenshots for posterity's sake?

**Comment by rjayasin** [comment]
@j-delaney, sure, clicking apply now on any job page, e.g. 

![1a](https://user-images.githubusercontent.com/4087768/27749391-41f527b4-5d88-11e7-9f18-688b7311b5b1.PNG)

brings you to this screen 

![1](https://user-images.githubusercontent.com/4087768/27749402-503d63b8-5d88-11e7-81a1-0aa0430c15ed.PNG)

that requires account creation in order to submit for any jobs.

![2](https://user-images.githubusercontent.com/4087768/27749420-65e26b1e-5d88-11e7-811b-527ceea8be7c.PNG)

**Comment by j-delaney** [comment]
Great! Could you please open a PR to remove them?
