### ISSUE TITLE
Categorize by country?

### ISSUE THREAD

**Issue by michael34** [j-delaney/easy-application#84]
I would like to see this list split up by country. What do you think?

**Comment by j-delaney** [comment]
I completely understand wanting to have it organized by country, but my goal is to keep the list as simple as possible. I think organizing by country adds some complexity that isn't 100% needed. I appreciate the suggestion though and would still be happy to talk about this more if you're interested! :)

**Comment by michael34** [comment]
@j-delaney I think that's a valid goal. Thanks for the reply.

**Comment by NerdDiffer** [comment]
@michael34, I've made a [parser](https://github.com/NerdDiffer/easy-application-parser) for this list. Though it does not categorize by country out of the box, it could used to build a filter.

**Comment by pankajpatel** [comment]
The parser can stay as a github project page and that page can have all the features.
